services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: ssehub
      POSTGRES_USER: ssehub
      POSTGRES_PASSWORD: ssehub
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
